---
parse:
  title: "Talk:UMS Prometheus (ship)"
  text:
    text: "<p>The reference \"UMS Prometheus\" will be required for a map page when\
      \ I do the RtNP maps. Is there any chance this page could be renamed \"UMS Prometheus\
      \ (Ship)\"&#160;?--<a href=\"/edit/User:Hellscrag?redlink=1\" class=\"new\"\
      \ title=\"User:Hellscrag (page does not exist)\">Hellscrag</a> 19:19, 27 July\
      \ 2007 (EDT)\n</p>\n<dl><dd>Done. Anyone can move pages, by the way (with the\
      \ Move button up top), and this request was certainly reasonable. Though, thinking\
      \ about it now <i>after</i> I've gone and moved it, would it be feasible to\
      \ integrate the ship description and details into the later walkthrough? <a\
      \ href=\"/User:Gnomre\" title=\"User:Gnomre\">Gnomre</a> 19:31, 27 July 2007\
      \ (EDT)</dd></dl>\n<dl><dd>It may well be possible - or it might be better just\
      \ to put the text on the RtNP main page. We'll see.--<a href=\"/edit/User:Hellscrag?redlink=1\"\
      \ class=\"new\" title=\"User:Hellscrag (page does not exist)\">Hellscrag</a>\
      \ 11:29, 28 July 2007 (EDT)</dd></dl>\n\n<!-- \nNewPP limit report\nCached time:\
      \ 20221207053704\nCache expiry: 86400\nDynamic content: false\nCPU time usage:\
      \ 0.031 seconds\nReal time usage: 0.056 seconds\nPreprocessor visited node count:\
      \ 1/1000000\nPreprocessor generated node count: 4/1000000\nPostâ€expand include\
      \ size: 0/2097152 bytes\nTemplate argument size: 0/2097152 bytes\nHighest expansion\
      \ depth: 1/40\nExpensive parser function count: 0/100\n-->\n<!--\nTransclusion\
      \ expansion time report (%,ms,calls,template)\n100.00%    0.000      1 -total\n\
      -->\n\n<!-- Saved in parser cache with key liandri:pcache:idhash:1955-0!*!0!*!*!*!*\
      \ and timestamp 20221207053703 and revision id 3289\n -->\n"
  categories: []
  links:
  - ns: 2
    exists: true
    name: "User:Gnomre"
  - ns: 2
    exists: false
    name: "User:Hellscrag"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "Talk:UMS Prometheus (ship)"
  iwlinks: []
  wikitext:
    text: "The reference \"UMS Prometheus\" will be required for a map page when I\
      \ do the RtNP maps. Is there any chance this page could be renamed \"UMS Prometheus\
      \ (Ship)\" ?--[[User:Hellscrag|Hellscrag]] 19:19, 27 July 2007 (EDT)\n:Done.\
      \ Anyone can move pages, by the way (with the Move button up top), and this\
      \ request was certainly reasonable. Though, thinking about it now ''after''\
      \ I've gone and moved it, would it be feasible to integrate the ship description\
      \ and details into the later walkthrough? [[User:Gnomre|Gnomre]] 19:31, 27 July\
      \ 2007 (EDT)\n\n:It may well be possible - or it might be better just to put\
      \ the text on the RtNP main page. We'll see.--[[User:Hellscrag|Hellscrag]] 11:29,\
      \ 28 July 2007 (EDT)"
  properties: []
  revId: 3289
name: "Talk:UMS Prometheus (ship)"
revision:
  revid: 3289
  parentid: 3278
  user: "Hellscrag"
  timestamp: 1185636566.000000000
  comment: ""
timestamp: 1670391424.267982000
isRedirect: false
