---
parse:
  title: "UMS Prometheus (ship)"
  text:
    text: "<dl><dd><i>For the mission, see <a href=\"/UMS_Prometheus\" title=\"UMS\
      \ Prometheus\">UMS Prometheus</a>.</i></dd></dl>\n<div class=\"thumb tright\"\
      ><div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/File:UMS_Prometheus.jpg\"\
      \ class=\"image\"><img alt=\"\" src=\"/w/images/thumb/UMS_Prometheus.jpg/300px-UMS_Prometheus.jpg\"\
      \ width=\"300\" height=\"119\" class=\"thumbimage\" srcset=\"/w/images/thumb/UMS_Prometheus.jpg/450px-UMS_Prometheus.jpg\
      \ 1.5x, /w/images/thumb/UMS_Prometheus.jpg/600px-UMS_Prometheus.jpg 2x\" /></a>\
      \  <div class=\"thumbcaption\"><div class=\"magnify\"><a href=\"/File:UMS_Prometheus.jpg\"\
      \ class=\"internal\" title=\"Enlarge\"></a></div>The UMS Prometheus</div></div></div>\n\
      <p>The <b>UMS Prometheus</b> is a <a href=\"/Unified_Military_Services\" title=\"\
      Unified Military Services\">Unified Military Services</a> Cruiser, that crashed\
      \ on the planet <a href=\"/Na_Pali\" title=\"Na Pali\">Na Pali</a>. The vessel\
      \ crashed in a shallow valley not far from <a href=\"/Glathriel_Village_(part_1)\"\
      \ title=\"Glathriel Village (part 1)\">Glathriel Village</a> and the <a href=\"\
      /Spire_Valley\" title=\"Spire Valley\">Spire Valley</a>, and was split into\
      \ three pieces due to the impact. As she impacted, parts and supplies from the\
      \ vessel landed around the area, particulary in Glatherial Village. \nThe ship\
      \ was a mess after landing. One of the engine cores melted down and flooded\
      \ the engine room with molten steel. The lower barracks were flooded due to\
      \ a broken pipe. Half of the upper barracks collapsed, and one turbolift and\
      \ door were malfunctioning. Most of her crew have been killed or got crushed\
      \ in the doors of \na Turbo-Lift when managing to escape. The ship was also\
      \ infested with <a href=\"/Mercenaries\" class=\"mw-redirect\" title=\"Mercenaries\"\
      >Mercenaries</a>, who were salvaging useful parts of the cruiser. \n</p><p><a\
      \ href=\"/Prisoner_849\" title=\"Prisoner 849\">Prisoner 849</a>, escapee of\
      \ the <a href=\"/UMS_Vortex_Rikers\" title=\"UMS Vortex Rikers\">UMS Vortex\
      \ Rikers</a>, was sent by the <a href=\"/UMS_Bodega_Bay\" title=\"UMS Bodega\
      \ Bay\">UMS Bodega Bay</a> to recover the Prometheus's Data Cores. After she\
      \ activated the ELT transmitter on the bridge, marines from the Bodega Bay were\
      \ sent to execute her, at which they failed. The ship was abandoned after that\
      \ battle.\n</p>\n<!-- \nNewPP limit report\nCached time: 20221121190933\nCache\
      \ expiry: 86400\nDynamic content: false\nCPU time usage: 0.068 seconds\nReal\
      \ time usage: 0.155 seconds\nPreprocessor visited node count: 10/1000000\nPreprocessor\
      \ generated node count: 88/1000000\nPostâ€expand include size: 62/2097152 bytes\n\
      Template argument size: 39/2097152 bytes\nHighest expansion depth: 3/40\nExpensive\
      \ parser function count: 0/100\n-->\n<!--\nTransclusion expansion time report\
      \ (%,ms,calls,template)\n100.00%    9.285      1 -total\n100.00%    9.285  \
      \    1 Template:For\n-->\n\n<!-- Saved in parser cache with key liandri:pcache:idhash:1943-0!*!0!*!*!5!*\
      \ and timestamp 20221121190933 and revision id 11436\n -->\n"
  categories:
  - sortkey: ""
    name: "Spaceships"
  links:
  - ns: 0
    exists: true
    name: "UMS Prometheus"
  - ns: 0
    exists: true
    name: "Mercenaries"
  - ns: 0
    exists: true
    name: "Unified Military Services"
  - ns: 0
    exists: true
    name: "Spire Valley"
  - ns: 0
    exists: true
    name: "Glathriel Village (part 1)"
  - ns: 0
    exists: true
    name: "Prisoner 849"
  - ns: 0
    exists: true
    name: "Na Pali"
  - ns: 0
    exists: true
    name: "UMS Bodega Bay"
  - ns: 0
    exists: true
    name: "UMS Vortex Rikers"
  templates:
  - ns: 10
    exists: true
    name: "Template:For"
  images:
  - "UMS_Prometheus.jpg"
  externallinks: []
  sections: []
  displaytitle: "UMS Prometheus (ship)"
  iwlinks: []
  wikitext:
    text: "{{for|the mission|UMS Prometheus}}\n[[Image:UMS Prometheus.jpg|thumb|The\
      \ UMS Prometheus]]\nThe '''UMS Prometheus''' is a [[Unified Military Services]]\
      \ Cruiser, that crashed on the planet [[Na Pali]]. The vessel crashed in a shallow\
      \ valley not far from [[Glathriel Village (part 1)|Glathriel Village]] and the\
      \ [[Spire Valley]], and was split into three pieces due to the impact. As she\
      \ impacted, parts and supplies from the vessel landed around the area, particulary\
      \ in Glatherial Village. \nThe ship was a mess after landing. One of the engine\
      \ cores melted down and flooded the engine room with molten steel. The lower\
      \ barracks were flooded due to a broken pipe. Half of the upper barracks collapsed,\
      \ and one turbolift and door were malfunctioning. Most of her crew have been\
      \ killed or got crushed in the doors of \na Turbo-Lift when managing to escape.\
      \ The ship was also infested with [[Mercenaries]], who were salvaging useful\
      \ parts of the cruiser. \n\n[[Prisoner 849]], escapee of the [[UMS Vortex Rikers]],\
      \ was sent by the [[UMS Bodega Bay]] to recover the Prometheus's Data Cores.\
      \ After she activated the ELT transmitter on the bridge, marines from the Bodega\
      \ Bay were sent to execute her, at which they failed. The ship was abandoned\
      \ after that battle.\n\n[[Category:Spaceships]]"
  properties: []
  revId: 11436
name: "UMS Prometheus (ship)"
revision:
  revid: 11436
  parentid: 11273
  user: "Fulsam"
  timestamp: 1239752350.000000000
  comment: ""
timestamp: 1669122202.062023000
isRedirect: false
