---
parse:
  title: "Category:Applications"
  text:
    text: "<p>This <a href=\"/Unreal_Wiki:Categories\" title=\"Unreal Wiki:Categories\"\
      >category</a> contains a list of programs that can be used for Unreal modding.</p>\n\
      \n<!-- \nNewPP limit report\nCPU time usage: 0.012 seconds\nReal time usage:\
      \ 0.029 seconds\nPreprocessor visited node count: 2/1000000\nPreprocessor generated\
      \ node count: 12/1000000\nPostâ€expand include size: 12/2097152 bytes\nTemplate\
      \ argument size: 0/2097152 bytes\nHighest expansion depth: 2/40\nExpensive parser\
      \ function count: 0/100\n-->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n\
      100.00%    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key\
      \ wiki:pcache:idhash:259-0!*!0!*!*!*!* and timestamp 20221117232326 and revision\
      \ id 46016\n -->\n"
  categories:
  - sortkey: " Applications"
    name: "Article_categories"
  links:
  - ns: 4
    exists: true
    name: "Unreal Wiki:Categories"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "Category:Applications"
  iwlinks: []
  wikitext:
    text: "This [[Project:Categories|category]] contains a list of programs that can\
      \ be used for Unreal modding.\n\n[[Category:Article categories| {{PAGENAME}}]]"
  properties: []
  revId: 46016
name: "Category:Applications"
revision:
  revid: 46016
  parentid: 46002
  user: "Wormbo"
  timestamp: 1403275905.000000000
  comment: "reverted because UDK is only one implementation of the Unreal Engine,\
    \ while this site wants to cover all of them"
timestamp: 1668752613.158226000
