---
parse:
  title: "Config"
  text:
    text: "<table style=\"font-style: italic;\" class=\"metadata plainlinks ambox\
      \ ambox-info\">\n<tr>\n<td class=\"ambox-image\">\n<div style=\"width:52px;\"\
      ><a href=\"/File:Disambig.png\" class=\"image\"><img alt=\"Disambig.png\" src=\"\
      /w/images/Disambig.png\" width=\"30\" height=\"23\" /></a></div>\n</td>\n<td\
      \ class=\"ambox-text\">This disambiguation page lists articles associated with\
      \ the same title.<br />\nIf an <a href=\"/Special:WhatLinksHere/Config\" title=\"\
      Special:WhatLinksHere/Config\">internal link</a> led you here, you may wish\
      \ to change the link to point directly to the intended article.</td>\n</tr>\n\
      </table>\n<p>The keyword <b>config</b> is used:</p>\n<ul>\n<li>as a modifier\
      \ for declaring <a href=\"/Variables\" title=\"Variables\">variables</a> configurable\
      \ <a href=\"/Variables#Modifiers_affecting_values\" title=\"Variables\">config</a></li>\n\
      <li>as a modifier for declaring <a href=\"/Class\" title=\"Class\" class=\"\
      mw-redirect\">classes</a> configurable <a href=\"/Classes#Modifiers\" title=\"\
      Classes\">config</a></li>\n</ul>\n<h2><span class=\"mw-headline\" id=\"See_also\"\
      >See also</span><span class=\"mw-editsection\"><span class=\"mw-editsection-bracket\"\
      >[</span><a href=\"/edit/Config?section=1\" title=\"Edit section: See also\"\
      >edit</a><span class=\"mw-editsection-bracket\">]</span></span></h2>\n<ul>\n\
      <li><a href=\"/GlobalConfig\" title=\"GlobalConfig\" class=\"mw-redirect\">GlobalConfig</a></li>\n\
      <li><a href=\"/StrictConfig\" title=\"StrictConfig\" class=\"mw-redirect\">StrictConfig</a></li>\n\
      <li><a href=\"/ParseConfig\" title=\"ParseConfig\" class=\"mw-redirect\">ParseConfig</a></li>\n\
      <li><a href=\"/PerObjectConfig\" title=\"PerObjectConfig\" class=\"mw-redirect\"\
      >PerObjectConfig</a></li>\n</ul>\n\n<!-- \nNewPP limit report\nCPU time usage:\
      \ 0.052 seconds\nReal time usage: 0.055 seconds\nPreprocessor visited node count:\
      \ 38/1000000\nPreprocessor generated node count: 183/1000000\nPostâ€expand include\
      \ size: 977/2097152 bytes\nTemplate argument size: 287/2097152 bytes\nHighest\
      \ expansion depth: 4/40\nExpensive parser function count: 0/100\n-->\n\n<!--\
      \ \nTransclusion expansion time report (%,ms,calls,template)\n100.00%    7.442\
      \      1 - -total\n100.00%    7.442      1 - Template:Disambig\n 65.44%    4.870\
      \      1 - Template:Ambox\n-->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:28992-0!*!0!*!*!5!*\
      \ and timestamp 20221117154414 and revision id 43840\n -->\n"
  categories:
  - sortkey: "Config"
    name: "Disambiguation"
  links:
  - ns: 0
    exists: true
    name: "Classes"
  - ns: 0
    exists: true
    name: "StrictConfig"
  - ns: 0
    exists: true
    name: "GlobalConfig"
  - ns: 0
    exists: true
    name: "ParseConfig"
  - ns: 0
    exists: true
    name: "PerObjectConfig"
  - ns: 0
    exists: true
    name: "Class"
  - ns: 0
    exists: true
    name: "Variables"
  templates:
  - ns: 10
    exists: true
    name: "Template:Disambig"
  - ns: 10
    exists: true
    name: "Template:Ambox"
  images:
  - "Disambig.png"
  externallinks: []
  sections:
  - toclevel: 1
    level: "2"
    line: "See also"
    number: "1"
    index: "1"
    fromtitle: "Config"
    byteoffset: 243
    anchor: "See_also"
  displaytitle: "Config"
  iwlinks: []
  wikitext:
    text: "{{disambig}}\nThe keyword '''config''' is used:\n* as a modifier for declaring\
      \ [[variables]] configurable [[Variables#Modifiers_affecting_values|config]]\n\
      * as a modifier for declaring [[class|classes]] configurable [[Classes#Modifiers|config]]\n\
      \n==See also==\n* [[GlobalConfig]]\n* [[StrictConfig]]\n* [[ParseConfig]]\n\
      * [[PerObjectConfig]]"
  properties: []
  revId: 43840
name: "Config"
revision:
  revid: 43840
  parentid: 43428
  user: "Wormbo"
  timestamp: 1281344231.000000000
  comment: "/* See also */"
timestamp: 1668759881.166280000
