---
parse:
  title: "GlobalConfig"
  text:
    text: "<div class=\"redirectMsg\"><p>Redirect to:</p><ul class=\"redirectText\"\
      ><li><a href=\"/Variables?redirect=no#Modifiers_affecting_values\" title=\"\
      Variables\">Variables#Modifiers affecting values</a></li></ul></div>\n<!-- \n\
      NewPP limit report\nCPU time usage: 0.007 seconds\nReal time usage: 0.023 seconds\n\
      Preprocessor visited node count: 0/1000000\nPreprocessor generated node count:\
      \ 2/1000000\nPostâ€expand include size: 0/2097152 bytes\nTemplate argument size:\
      \ 0/2097152 bytes\nHighest expansion depth: 0/40\nExpensive parser function\
      \ count: 0/100\n-->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n\
      100.00%    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key\
      \ wiki:pcache:idhash:28993-0!*!*!*!*!*!* and timestamp 20221118083345 and revision\
      \ id 43424\n -->\n"
  categories: []
  links:
  - ns: 0
    exists: true
    name: "Variables"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "GlobalConfig"
  iwlinks: []
  wikitext:
    text: "#Redirect [[Variables#Modifiers_affecting_values]]"
  properties: []
  revId: 43424
name: "GlobalConfig"
revision:
  revid: 43424
  parentid: 0
  user: "Eliot"
  timestamp: 1276132431.000000000
  comment: "Redirected page to [[Variables#Modifiers affecting values]]"
timestamp: 1668760425.665900000
