---
parse:
  title: "Legacy:Model Conversion Application"
  text:
    text: "<p>Some very good model conversion applications are:</p>\n<p>-<a href=\"\
      /Legacy:MilkShape\" title=\"Legacy:MilkShape\">MilkShape</a> 3d:-</p>\n<pre>\
      \ -Import model\n -Press Ctrl+T to use Texture Cordinate Editor\n -Name the\
      \ material as the EXACT texture used.\n - Spaces in filenames usually are converted\
      \ to underscores \" _ \" so point to this\n -EG: Material applied is \"grey\
      \ block.tga\" then the name would be \"grey_block.tga\"\n -Press rename after\
      \ you put in the name to finalize renaming\n -Rename is under the material list\
      \ box\n -Select a material first tho\n</pre>\n<p>-Quick3d-</p>\n<pre>-it is\
      \ free if you register\n-it can convert easily but some older versions of models\
      \ won't work\n</pre>\n<p>-<a href=\"/Legacy:3D_Studio_Max\" title=\"Legacy:3D\
      \ Studio Max\">3D Studio Max</a>-</p>\n<pre>-commercial tool\n-it is powerful,\
      \ but ver expensive ($1200)\n</pre>\n<hr />\n<p><b>Tarquin:</b> Hi! Thanks for\
      \ adding content, whoever you are. But please take a minute to learn <a href=\"\
      /Legacy:Wiki_Markup\" title=\"Legacy:Wiki Markup\">wiki markup</a> so your pages\
      \ are nicely formatted&#160;:)</p>\n\n<!-- \nNewPP limit report\nCPU time usage:\
      \ 0.014 seconds\nReal time usage: 0.030 seconds\nPreprocessor visited node count:\
      \ 1/1000000\nPreprocessor generated node count: 4/1000000\nPostâ€expand include\
      \ size: 0/2097152 bytes\nTemplate argument size: 0/2097152 bytes\nHighest expansion\
      \ depth: 1/40\nExpensive parser function count: 0/100\n-->\n\n<!-- \nTransclusion\
      \ expansion time report (%,ms,calls,template)\n100.00%    0.000      1 - -total\n\
      -->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:2242-0!*!0!*!*!*!*\
      \ and timestamp 20221118025352 and revision id 5416\n -->\n"
  categories: []
  links:
  - ns: 100
    exists: true
    name: "Legacy:3D Studio Max"
  - ns: 100
    exists: true
    name: "Legacy:Wiki Markup"
  - ns: 100
    exists: true
    name: "Legacy:MilkShape"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "Legacy:Model Conversion Application"
  iwlinks: []
  wikitext:
    text: "Some very good model conversion applications are:\n\n-[[Legacy:MilkShape|MilkShape]]\
      \ 3d:-\n  -Import model\n  -Press Ctrl+T to use Texture Cordinate Editor\n \
      \ -Name the material as the EXACT texture used.\n  - Spaces in filenames usually\
      \ are converted to underscores \" _ \" so point to this\n  -EG: Material applied\
      \ is \"grey block.tga\" then the name would be \"grey_block.tga\"\n  -Press\
      \ rename after you put in the name to finalize renaming\n  -Rename is under\
      \ the material list box\n  -Select a material first tho\n\n-Quick3d-\n -it is\
      \ free if you register\n -it can convert easily but some older versions of models\
      \ won't work\n\n-[[Legacy:3D Studio Max|3D Studio Max]]-\n\n -commercial tool\n\
      \ -it is powerful, but ver expensive ($1200)\n\n----\n\n'''Tarquin:''' Hi! Thanks\
      \ for adding content, whoever you are. But please take a minute to learn [[Legacy:Wiki\
      \ Markup|wiki markup]] so your pages are nicely formatted :)"
  properties: []
  revId: 5416
name: "Legacy:Model Conversion Application"
revision:
  revid: 5416
  parentid: 5418
  user: "Tarquin"
  timestamp: 1170319355.000000000
  comment: ""
timestamp: 1668766285.103997000
