---
parse:
  title: "Legacy:Environment Mapping"
  text:
    text: "<p>This is a simple, and shortened definition of its use within Unreal\
      \ Tournament.</p>\n<p>Basically, an object is made to reflect an arbitrary image\
      \ (or texture) by placing the said image on the inside surface of a cube or\
      \ sphere, then mathematically placing the selected object inside the cube/sphere\
      \ where the inside surface of the cube/sphere (covered with the image) is reflected.\
      \ Used best with a texture that will look natural when reflected but obscured\
      \ enough to be unrecognizable. E.g. a solid color texture will not work.</p>\n\
      <p>Using this usually just gives the illusion of reflectivity or \"shininess\"\
      \ on a mesh, with a similar effect to skyboxes in reference to \"point of perspective\"\
      .</p>\n<p>Another form of environment mapping is making an object reflect its\
      \ surroundings dynamically, much like the mirror option for surface properties\
      \ of world geometry in maps. This method involves quite complex operations and\
      \ a lot of slow down if used frequently. The calculations are simpler in the\
      \ previous case. (<b>Foxpaw:</b> How can we set a material to do this?)</p>\n\
      <p><b>AlphaOne:</b> I think that <a rel=\"nofollow\" class=\"external text\"\
      \ href=\"http://www.marblemadness2003.com\">marblemadness2003</a> mod does dynamic\
      \ reflections. Here is what they say they did: <a rel=\"nofollow\" class=\"\
      external text\" href=\"http://www.marblemadness2003.com/forum/viewtopic.php?t=2&amp;highlight=environment\"\
      >forum thread</a></p>\n<p><b>Foxpaw:</b> Unless I'm reading that wrong.. they\
      \ explicitly state that they did not use dynamic reflections on that thread.</p>\n\
      <p><b>AOANLA:</b> You are reading it wrong. Apparently they generate a new environment\
      \ map each frame, and pass that to the rendering code, as UT 2003 itself doesn't\
      \ generate dynamic maps. So... it's a workaround.</p>\n<p><b>AlphaOne:</b> It\
      \ looks like they have a problem with tiling.</p>\n<p>Here is a diagram of the\
      \ latter method. (not really used int Unreal, but helps understand the concept)</p>\n\
      <div class=\"center\">\n<div class=\"floatnone\"><a href=\"/File:Legacy_shinymap.jpeg\"\
      \ class=\"image\" title=\"Dont remember the site i got this from, but it was\
      \ made by Scott Ruggels\"><img alt=\"Dont remember the site i got this from,\
      \ but it was made by Scott Ruggels\" src=\"/w/images/Legacy_shinymap.jpeg\"\
      \ width=\"450\" height=\"450\" /></a></div>\n</div>\n<h2><span class=\"mw-headline\"\
      \ id=\"Links\">Links</span><span class=\"mw-editsection\"><span class=\"mw-editsection-bracket\"\
      >[</span><a href=\"/edit/Legacy:Environment_Mapping?section=1\" title=\"Edit\
      \ section: Links\">edit</a><span class=\"mw-editsection-bracket\">]</span></span></h2>\n\
      <ul>\n<li>Here is another link with pictures: <a rel=\"nofollow\" class=\"external\
      \ free\" href=\"http://home.san.rr.com/thereindels/Mapping/Mapping.html\">http://home.san.rr.com/thereindels/Mapping/Mapping.html</a></li>\n\
      </ul>\n<hr />\n<p><a href=\"/Category:Legacy_To_Do\" title=\"Category:Legacy\
      \ To Do\">Category:Legacy To Do</a> - There should be some description of how\
      \ to do this in UnrealED. Also both the links above are broken!</p>\n\n<!--\
      \ \nNewPP limit report\nCPU time usage: 0.055 seconds\nReal time usage: 0.057\
      \ seconds\nPreprocessor visited node count: 4/1000000\nPreprocessor generated\
      \ node count: 16/1000000\nPostâ€expand include size: 19/2097152 bytes\nTemplate\
      \ argument size: 0/2097152 bytes\nHighest expansion depth: 2/40\nExpensive parser\
      \ function count: 0/100\n-->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n\
      100.00%    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key\
      \ wiki:pcache:idhash:1125-0!*!0!*!*!5!* and timestamp 20221118014555 and revision\
      \ id 2958\n -->\n"
  categories:
  - sortkey: "Environment Mapping"
    name: "Legacy_To_Do"
  links:
  - ns: 14
    exists: true
    name: "Category:Legacy To Do"
  templates: []
  images:
  - "Legacy_shinymap.jpeg"
  externallinks:
  - "http://home.san.rr.com/thereindels/Mapping/Mapping.html"
  - "http://www.marblemadness2003.com"
  - "http://www.marblemadness2003.com/forum/viewtopic.php?t=2&highlight=environment"
  sections:
  - toclevel: 1
    level: "2"
    line: "Links"
    number: "1"
    index: "1"
    fromtitle: "Legacy:Environment_Mapping"
    byteoffset: 1909
    anchor: "Links"
  displaytitle: "Legacy:Environment Mapping"
  iwlinks: []
  wikitext:
    text: "This is a simple, and shortened definition of its use within Unreal Tournament.\n\
      \nBasically, an object is made to reflect an arbitrary image (or texture) by\
      \ placing the said image on the inside surface of a cube or sphere, then mathematically\
      \ placing the selected object inside the cube/sphere where the inside surface\
      \ of the cube/sphere (covered with the image) is reflected. Used best with a\
      \ texture that will look natural when reflected but obscured enough to be unrecognizable.\
      \ E.g. a solid color texture will not work.\n\nUsing this usually just gives\
      \ the illusion of reflectivity or \"shininess\" on a mesh, with a similar effect\
      \ to skyboxes in reference to \"point of perspective\". \n\nAnother form of\
      \ environment mapping is making an object reflect its surroundings dynamically,\
      \ much like the mirror option for surface properties of world geometry in maps.\
      \ This method involves quite complex operations and a lot of slow down if used\
      \ frequently. The calculations are simpler in the previous case. ('''Foxpaw:'''\
      \ How can we set a material to do this?)\n\n'''AlphaOne:''' I think that [http://www.marblemadness2003.com\
      \ marblemadness2003] mod does dynamic reflections. Here is what they say they\
      \ did: [http://www.marblemadness2003.com/forum/viewtopic.php?t=2&highlight=environment\
      \ forum thread]\n\n'''Foxpaw:''' Unless I'm reading that wrong.. they explicitly\
      \ state that they did not use dynamic reflections on that thread.\n\n'''AOANLA:'''\
      \ You are reading it wrong. Apparently they generate a new environment map each\
      \ frame, and pass that to the rendering code, as UT 2003 itself doesn't generate\
      \ dynamic maps. So... it's a workaround.\n\n'''AlphaOne:''' It looks like they\
      \ have a problem with tiling.\n\nHere is a diagram of the latter method. (not\
      \ really used int Unreal, but helps understand the concept)\n\n[[Image:Legacy_shinymap.jpeg|center|Dont\
      \ remember the site i got this from, but it was made by Scott Ruggels]]\n\n\
      ==Links ==\n* Here is another link with pictures: http://home.san.rr.com/thereindels/Mapping/Mapping.html\n\
      \n----\n\n[[:Category:Legacy To Do]] - There should be some description of how\
      \ to do this in UnrealED.  Also both the links above are broken!\n[[Category:Legacy\
      \ To Do|{{PAGENAME}}]]"
  properties: []
  revId: 2958
name: "Legacy:Environment Mapping"
revision:
  revid: 2958
  parentid: 2960
  user: "Dkgamez"
  timestamp: 1085252079.000000000
  comment: "Dead link"
timestamp: 1668765147.759266000
