---
parse:
  title: "Light color values"
  text:
    text: "<div class=\"redirectMsg\"><p>Redirect to:</p><ul class=\"redirectText\"\
      ><li><a href=\"/Light_colors_reference?redirect=no\" title=\"Light colors reference\"\
      >Light colors reference</a></li></ul></div>\n<!-- \nNewPP limit report\nCPU\
      \ time usage: 0.006 seconds\nReal time usage: 0.015 seconds\nPreprocessor visited\
      \ node count: 0/1000000\nPreprocessor generated node count: 2/1000000\nPostâ€\
      expand include size: 0/2097152 bytes\nTemplate argument size: 0/2097152 bytes\n\
      Highest expansion depth: 0/40\nExpensive parser function count: 0/100\n-->\n\
      \n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n100.00% \
      \   0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:24416-0!*!*!*!*!*!*\
      \ and timestamp 20221118065024 and revision id 42686\n -->\n"
  categories: []
  links:
  - ns: 0
    exists: true
    name: "Light colors reference"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "Light color values"
  iwlinks: []
  wikitext:
    text: "#REDIRECT [[Light colors reference]]"
  properties: []
  revId: 42686
name: "Light color values"
revision:
  revid: 42686
  parentid: 35499
  user: "Wormbo"
  timestamp: 1269343587.000000000
  comment: "Redirected page to [[Light colors reference]]"
timestamp: 1668754224.887583000
