---
parse:
  title: "StrictConfig"
  text:
    text: "<div class=\"redirectMsg\"><p>Redirect to:</p><ul class=\"redirectText\"\
      ><li><a href=\"/Structs?redirect=no#Modifiers_affecting_values\" title=\"Structs\"\
      >Structs#Modifiers affecting values</a></li></ul></div>\n<!-- \nNewPP limit\
      \ report\nCPU time usage: 0.007 seconds\nReal time usage: 0.008 seconds\nPreprocessor\
      \ visited node count: 0/1000000\nPreprocessor generated node count: 2/1000000\n\
      Postâ€expand include size: 0/2097152 bytes\nTemplate argument size: 0/2097152\
      \ bytes\nHighest expansion depth: 0/40\nExpensive parser function count: 0/100\n\
      -->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n100.00%\
      \    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:28997-0!*!*!*!*!*!*\
      \ and timestamp 20221118083819 and revision id 43429\n -->\n"
  categories: []
  links:
  - ns: 0
    exists: true
    name: "Structs"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "StrictConfig"
  iwlinks: []
  wikitext:
    text: "#Redirect [[Structs#Modifiers_affecting_values]]"
  properties: []
  revId: 43429
name: "StrictConfig"
revision:
  revid: 43429
  parentid: 0
  user: "Eliot"
  timestamp: 1276132941.000000000
  comment: "Redirected page to [[Structs#Modifiers affecting values]]"
timestamp: 1668760699.359571000
